Update speedtest

diff --git a/speedtest b/speedtest
--- a/speedtest
+++ b/speedtest
@@ -1,20 +1,18 @@
 #!/bin/bash
-if command -v flock &>/dev/null; then
-  # Get the script's filename without path
-  directory_name=$(dirname "$0")
-  script_name=$(basename "$0")
-  # Generate a unique lock file name by combining the directory name and script name,
-  # converting them to lowercase, replacing spaces and non-alphanumeric characters with hyphens,
-  locked_name="${directory_name}-${script_name}-by-${USER}"
-  locked_name=$(echo "$locked_name" | tr '[:upper:]' '[:lower:]') # Convert to lowercase
-  locked_name=$(echo "$locked_name" | sed -E 's/[^a-z0-9]+/-/g')  # Replace spaces and non-alphanumeric characters with hyphens
-  locked_name=$(echo "$locked_name" | sed -E 's/^-+|-+$//g')      # Remove any extra hyphens at the beginning or end of the string
-  mkdir -p /tmp/hungng-locked && chmod 0777 /tmp/hungng-locked
-  locked_filename="/tmp/hungng-locked/${locked_name}.lock"
-  # Lock the script so that only one instance can run at a time.
-  exec 200>"${locked_filename}" || exit 1
-  flock -n 200 || exit 1
-fi
+# Get the script's filename without path
+directory_name=$(dirname "$0")
+script_name=$(basename "$0")
+# Generate a unique lock file name by combining the directory name and script name,
+# converting them to lowercase, replacing spaces and non-alphanumeric characters with hyphens,
+locked_name="${directory_name}-${script_name}-by-${USER}"
+locked_name=$(echo "$locked_name" | tr '[:upper:]' '[:lower:]') # Convert to lowercase
+locked_name=$(echo "$locked_name" | sed -E 's/[^a-z0-9]+/-/g')  # Replace spaces and non-alphanumeric characters with hyphens
+locked_name=$(echo "$locked_name" | sed -E 's/^-+|-+$//g')      # Remove any extra hyphens at the beginning or end of the string
+mkdir -p /tmp/hungng-locked && chmod 0777 /tmp/hungng-locked
+locked_filename="/tmp/hungng-locked/${locked_name}.lock"
+# Lock the script so that only one instance can run at a time.
+exec 200>"${locked_filename}" || exit 1
+flock -n 200 || exit 1
 SECONDS=0
 trap catch_abort INT
 function catch_abort() {
@@ -163,6 +161,13 @@ fetch_public_ipv6() {
 }
 # Example usage
 detected_os=$(os_name)
+
+# Check if the detected OS is supported
+if [[ "$detected_os" != "rhel" && "$detected_os" != "ubuntu" && "$detected_os" != "linux" ]]; then
+  message INFO "OS ${detected_os} is not supported!"
+  exit 1 # Exit the script with a non-zero status
+fi
+
 server_os_compatibility=$(grep '^ID_LIKE=' /etc/os-release | cut -d= -f2- | tr -d '"')
 os_compatibility="${server_os_compatibility^^}"
 message INFO "Detected OS: ${detected_os^^} - Compatible with: ${os_compatibility}"
